collectors:
  market_data:
    equities:
      enabled: true
      interval: 60  # Collect every 60 seconds
      tickers: ["AAPL", "MSFT", "GOOG"]  # Example tickers
    options:
      enabled: true
      interval: 120 # Collect every 120 seconds
      underlyings: ["AAPL", "SPY"]  # Example underlyings
    futures:
      enabled: true
      interval: 180  # Collect every 3 minutes
      symbols: ["ES=F", "NQ=F"]    # Example futures symbols (E-mini S&P 500, E-mini Nasdaq 100)
    crypto:
        enabled: true
        interval: 60
        assets: [ "BTC-USD", "ETH-USD"]
  unstructured_data:
    news:
      enabled: true
      interval: 3600  # Collect every hour
      sources:
        - url: "https://www.reuters.com/business/finance/"
          name: "Reuters Finance"
          headlines_selector: "h3.story-title"
          article_selector: "div.ArticleBodyWrapper p"
        - url: "https://www.bloomberg.com/markets"
          name: "Bloomberg Markets"
          headlines_selector: "a.story-list-story__info__headline-link"
          article_selector: "div.body-copy"

    twitter:
      enabled: true
      interval: 600  # Collect every 10 minutes
      accounts: ["@federalreserve", "@GoldmanSachs"]  # Example accounts

    reddit:
      enabled: true
      interval: 1800  # Collect every 30 minutes
      subreddits: ["wallstreetbets", "investing", "stocks"]  # Example subreddits

    sec_filings:
      enabled: true
      interval: 86400  # Collect once a day
      company_ciks: ["320193", "789019"]  # AAPL, MSFT (using CIKs)

    earnings_calls:
      enabled: true
      interval: 43200  # Every 12 hours
      companies:
        - name: "Seeking Alpha (AAPL)"
          url: "https://seekingalpha.com/symbol/AAPL/earnings/transcripts"
          transcript_selector: "a.transcript_title" #Example selector
          date_selector: "time.post-date" # Example Selector

  macro_data:
    fed_rates:
      enabled: true
      interval: 86400  # Once a day
    cpi:
      enabled: true
      interval: 86400  # Once a day (CPI is released monthly)
    geopolitical:
      enabled: true
      interval: 21600  # Every 6 hours
      sources:
        - url: "https://www.cfr.org/global-conflict-tracker" #Example URL
          name: "CFR Global Conflict Tracker"
          event_selector: "div.card-inner"  # Example selector
          title_selector: "h3.card-title"
          date_selector: "p.card-date"
          description_selector: "div.card-body"

storage:
  type: file  # Use file storage by default.  Change to "database" to use PostgreSQL.
  data_dir: "data"  # Directory for storing data (if using file storage)

  # Database settings (if using PostgreSQL; otherwise, ignored)
  database:
    enabled: false  # Set to true to use PostgreSQL
    user: your_db_user  # Replace with your database username
    password: your_db_password  # Replace with your database password
    host: your_db_host   # Replace with your database host (e.g., localhost)
    database: your_db_name  # Replace with your database name
    min_connections: 1
    max_connections: 10
    port: 5432

captcha:
  api_key: YOUR_ANTICAPTCHA_API_KEY  # Your AntiCaptcha API key (optional)

web_scraping:
    user_agents_file: "user_agents.txt"